package net.minidev.ovh.api.coretypes;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * IANA TimeZone names
 */
public enum OvhTimeZoneEnum {
	@JsonProperty("Africa/Abidjan")
	Africa_Abidjan("Africa/Abidjan"),
	@JsonProperty("Africa/Accra")
	Africa_Accra("Africa/Accra"),
	@JsonProperty("Africa/Addis_Ababa")
	Africa_Addis_Ababa("Africa/Addis_Ababa"),
	@JsonProperty("Africa/Algiers")
	Africa_Algiers("Africa/Algiers"),
	@JsonProperty("Africa/Asmara")
	Africa_Asmara("Africa/Asmara"),
	@JsonProperty("Africa/Bamako")
	Africa_Bamako("Africa/Bamako"),
	@JsonProperty("Africa/Bangui")
	Africa_Bangui("Africa/Bangui"),
	@JsonProperty("Africa/Banjul")
	Africa_Banjul("Africa/Banjul"),
	@JsonProperty("Africa/Bissau")
	Africa_Bissau("Africa/Bissau"),
	@JsonProperty("Africa/Blantyre")
	Africa_Blantyre("Africa/Blantyre"),
	@JsonProperty("Africa/Brazzaville")
	Africa_Brazzaville("Africa/Brazzaville"),
	@JsonProperty("Africa/Bujumbura")
	Africa_Bujumbura("Africa/Bujumbura"),
	@JsonProperty("Africa/Cairo")
	Africa_Cairo("Africa/Cairo"),
	@JsonProperty("Africa/Casablanca")
	Africa_Casablanca("Africa/Casablanca"),
	@JsonProperty("Africa/Ceuta")
	Africa_Ceuta("Africa/Ceuta"),
	@JsonProperty("Africa/Conakry")
	Africa_Conakry("Africa/Conakry"),
	@JsonProperty("Africa/Dakar")
	Africa_Dakar("Africa/Dakar"),
	@JsonProperty("Africa/Dar_es_Salaam")
	Africa_Dar_es_Salaam("Africa/Dar_es_Salaam"),
	@JsonProperty("Africa/Djibouti")
	Africa_Djibouti("Africa/Djibouti"),
	@JsonProperty("Africa/Douala")
	Africa_Douala("Africa/Douala"),
	@JsonProperty("Africa/El_Aaiun")
	Africa_El_Aaiun("Africa/El_Aaiun"),
	@JsonProperty("Africa/Freetown")
	Africa_Freetown("Africa/Freetown"),
	@JsonProperty("Africa/Gaborone")
	Africa_Gaborone("Africa/Gaborone"),
	@JsonProperty("Africa/Harare")
	Africa_Harare("Africa/Harare"),
	@JsonProperty("Africa/Johannesburg")
	Africa_Johannesburg("Africa/Johannesburg"),
	@JsonProperty("Africa/Juba")
	Africa_Juba("Africa/Juba"),
	@JsonProperty("Africa/Kampala")
	Africa_Kampala("Africa/Kampala"),
	@JsonProperty("Africa/Khartoum")
	Africa_Khartoum("Africa/Khartoum"),
	@JsonProperty("Africa/Kigali")
	Africa_Kigali("Africa/Kigali"),
	@JsonProperty("Africa/Kinshasa")
	Africa_Kinshasa("Africa/Kinshasa"),
	@JsonProperty("Africa/Lagos")
	Africa_Lagos("Africa/Lagos"),
	@JsonProperty("Africa/Libreville")
	Africa_Libreville("Africa/Libreville"),
	@JsonProperty("Africa/Lome")
	Africa_Lome("Africa/Lome"),
	@JsonProperty("Africa/Luanda")
	Africa_Luanda("Africa/Luanda"),
	@JsonProperty("Africa/Lubumbashi")
	Africa_Lubumbashi("Africa/Lubumbashi"),
	@JsonProperty("Africa/Lusaka")
	Africa_Lusaka("Africa/Lusaka"),
	@JsonProperty("Africa/Malabo")
	Africa_Malabo("Africa/Malabo"),
	@JsonProperty("Africa/Maputo")
	Africa_Maputo("Africa/Maputo"),
	@JsonProperty("Africa/Maseru")
	Africa_Maseru("Africa/Maseru"),
	@JsonProperty("Africa/Mbabane")
	Africa_Mbabane("Africa/Mbabane"),
	@JsonProperty("Africa/Mogadishu")
	Africa_Mogadishu("Africa/Mogadishu"),
	@JsonProperty("Africa/Monrovia")
	Africa_Monrovia("Africa/Monrovia"),
	@JsonProperty("Africa/Nairobi")
	Africa_Nairobi("Africa/Nairobi"),
	@JsonProperty("Africa/Ndjamena")
	Africa_Ndjamena("Africa/Ndjamena"),
	@JsonProperty("Africa/Niamey")
	Africa_Niamey("Africa/Niamey"),
	@JsonProperty("Africa/Nouakchott")
	Africa_Nouakchott("Africa/Nouakchott"),
	@JsonProperty("Africa/Ouagadougou")
	Africa_Ouagadougou("Africa/Ouagadougou"),
	@JsonProperty("Africa/Porto-Novo")
	Africa_Porto_Novo("Africa/Porto-Novo"),
	@JsonProperty("Africa/Sao_Tome")
	Africa_Sao_Tome("Africa/Sao_Tome"),
	@JsonProperty("Africa/Tripoli")
	Africa_Tripoli("Africa/Tripoli"),
	@JsonProperty("Africa/Tunis")
	Africa_Tunis("Africa/Tunis"),
	@JsonProperty("Africa/Windhoek")
	Africa_Windhoek("Africa/Windhoek"),
	@JsonProperty("America/Adak")
	America_Adak("America/Adak"),
	@JsonProperty("America/Anchorage")
	America_Anchorage("America/Anchorage"),
	@JsonProperty("America/Anguilla")
	America_Anguilla("America/Anguilla"),
	@JsonProperty("America/Antigua")
	America_Antigua("America/Antigua"),
	@JsonProperty("America/Araguaina")
	America_Araguaina("America/Araguaina"),
	@JsonProperty("America/Argentina/Buenos_Aires")
	America_Argentina_Buenos_Aires("America/Argentina/Buenos_Aires"),
	@JsonProperty("America/Argentina/Catamarca")
	America_Argentina_Catamarca("America/Argentina/Catamarca"),
	@JsonProperty("America/Argentina/Cordoba")
	America_Argentina_Cordoba("America/Argentina/Cordoba"),
	@JsonProperty("America/Argentina/Jujuy")
	America_Argentina_Jujuy("America/Argentina/Jujuy"),
	@JsonProperty("America/Argentina/La_Rioja")
	America_Argentina_La_Rioja("America/Argentina/La_Rioja"),
	@JsonProperty("America/Argentina/Mendoza")
	America_Argentina_Mendoza("America/Argentina/Mendoza"),
	@JsonProperty("America/Argentina/Rio_Gallegos")
	America_Argentina_Rio_Gallegos("America/Argentina/Rio_Gallegos"),
	@JsonProperty("America/Argentina/Salta")
	America_Argentina_Salta("America/Argentina/Salta"),
	@JsonProperty("America/Argentina/San_Juan")
	America_Argentina_San_Juan("America/Argentina/San_Juan"),
	@JsonProperty("America/Argentina/San_Luis")
	America_Argentina_San_Luis("America/Argentina/San_Luis"),
	@JsonProperty("America/Argentina/Tucuman")
	America_Argentina_Tucuman("America/Argentina/Tucuman"),
	@JsonProperty("America/Argentina/Ushuaia")
	America_Argentina_Ushuaia("America/Argentina/Ushuaia"),
	@JsonProperty("America/Aruba")
	America_Aruba("America/Aruba"),
	@JsonProperty("America/Asuncion")
	America_Asuncion("America/Asuncion"),
	@JsonProperty("America/Atikokan")
	America_Atikokan("America/Atikokan"),
	@JsonProperty("America/Bahia")
	America_Bahia("America/Bahia"),
	@JsonProperty("America/Bahia_Banderas")
	America_Bahia_Banderas("America/Bahia_Banderas"),
	@JsonProperty("America/Barbados")
	America_Barbados("America/Barbados"),
	@JsonProperty("America/Belem")
	America_Belem("America/Belem"),
	@JsonProperty("America/Belize")
	America_Belize("America/Belize"),
	@JsonProperty("America/Blanc-Sablon")
	America_Blanc_Sablon("America/Blanc-Sablon"),
	@JsonProperty("America/Boa_Vista")
	America_Boa_Vista("America/Boa_Vista"),
	@JsonProperty("America/Bogota")
	America_Bogota("America/Bogota"),
	@JsonProperty("America/Boise")
	America_Boise("America/Boise"),
	@JsonProperty("America/Cambridge_Bay")
	America_Cambridge_Bay("America/Cambridge_Bay"),
	@JsonProperty("America/Campo_Grande")
	America_Campo_Grande("America/Campo_Grande"),
	@JsonProperty("America/Cancun")
	America_Cancun("America/Cancun"),
	@JsonProperty("America/Caracas")
	America_Caracas("America/Caracas"),
	@JsonProperty("America/Cayenne")
	America_Cayenne("America/Cayenne"),
	@JsonProperty("America/Cayman")
	America_Cayman("America/Cayman"),
	@JsonProperty("America/Chicago")
	America_Chicago("America/Chicago"),
	@JsonProperty("America/Chihuahua")
	America_Chihuahua("America/Chihuahua"),
	@JsonProperty("America/Costa_Rica")
	America_Costa_Rica("America/Costa_Rica"),
	@JsonProperty("America/Creston")
	America_Creston("America/Creston"),
	@JsonProperty("America/Cuiaba")
	America_Cuiaba("America/Cuiaba"),
	@JsonProperty("America/Curacao")
	America_Curacao("America/Curacao"),
	@JsonProperty("America/Danmarkshavn")
	America_Danmarkshavn("America/Danmarkshavn"),
	@JsonProperty("America/Dawson")
	America_Dawson("America/Dawson"),
	@JsonProperty("America/Dawson_Creek")
	America_Dawson_Creek("America/Dawson_Creek"),
	@JsonProperty("America/Denver")
	America_Denver("America/Denver"),
	@JsonProperty("America/Detroit")
	America_Detroit("America/Detroit"),
	@JsonProperty("America/Dominica")
	America_Dominica("America/Dominica"),
	@JsonProperty("America/Edmonton")
	America_Edmonton("America/Edmonton"),
	@JsonProperty("America/Eirunepe")
	America_Eirunepe("America/Eirunepe"),
	@JsonProperty("America/El_Salvador")
	America_El_Salvador("America/El_Salvador"),
	@JsonProperty("America/Fortaleza")
	America_Fortaleza("America/Fortaleza"),
	@JsonProperty("America/Glace_Bay")
	America_Glace_Bay("America/Glace_Bay"),
	@JsonProperty("America/Godthab")
	America_Godthab("America/Godthab"),
	@JsonProperty("America/Goose_Bay")
	America_Goose_Bay("America/Goose_Bay"),
	@JsonProperty("America/Grand_Turk")
	America_Grand_Turk("America/Grand_Turk"),
	@JsonProperty("America/Grenada")
	America_Grenada("America/Grenada"),
	@JsonProperty("America/Guadeloupe")
	America_Guadeloupe("America/Guadeloupe"),
	@JsonProperty("America/Guatemala")
	America_Guatemala("America/Guatemala"),
	@JsonProperty("America/Guayaquil")
	America_Guayaquil("America/Guayaquil"),
	@JsonProperty("America/Guyana")
	America_Guyana("America/Guyana"),
	@JsonProperty("America/Halifax")
	America_Halifax("America/Halifax"),
	@JsonProperty("America/Havana")
	America_Havana("America/Havana"),
	@JsonProperty("America/Hermosillo")
	America_Hermosillo("America/Hermosillo"),
	@JsonProperty("America/Indiana/Indianapolis")
	America_Indiana_Indianapolis("America/Indiana/Indianapolis"),
	@JsonProperty("America/Indiana/Knox")
	America_Indiana_Knox("America/Indiana/Knox"),
	@JsonProperty("America/Indiana/Marengo")
	America_Indiana_Marengo("America/Indiana/Marengo"),
	@JsonProperty("America/Indiana/Petersburg")
	America_Indiana_Petersburg("America/Indiana/Petersburg"),
	@JsonProperty("America/Indiana/Tell_City")
	America_Indiana_Tell_City("America/Indiana/Tell_City"),
	@JsonProperty("America/Indiana/Vevay")
	America_Indiana_Vevay("America/Indiana/Vevay"),
	@JsonProperty("America/Indiana/Vincennes")
	America_Indiana_Vincennes("America/Indiana/Vincennes"),
	@JsonProperty("America/Indiana/Winamac")
	America_Indiana_Winamac("America/Indiana/Winamac"),
	@JsonProperty("America/Inuvik")
	America_Inuvik("America/Inuvik"),
	@JsonProperty("America/Iqaluit")
	America_Iqaluit("America/Iqaluit"),
	@JsonProperty("America/Jamaica")
	America_Jamaica("America/Jamaica"),
	@JsonProperty("America/Juneau")
	America_Juneau("America/Juneau"),
	@JsonProperty("America/Kentucky/Louisville")
	America_Kentucky_Louisville("America/Kentucky/Louisville"),
	@JsonProperty("America/Kentucky/Monticello")
	America_Kentucky_Monticello("America/Kentucky/Monticello"),
	@JsonProperty("America/Kralendijk")
	America_Kralendijk("America/Kralendijk"),
	@JsonProperty("America/La_Paz")
	America_La_Paz("America/La_Paz"),
	@JsonProperty("America/Lima")
	America_Lima("America/Lima"),
	@JsonProperty("America/Los_Angeles")
	America_Los_Angeles("America/Los_Angeles"),
	@JsonProperty("America/Lower_Princes")
	America_Lower_Princes("America/Lower_Princes"),
	@JsonProperty("America/Maceio")
	America_Maceio("America/Maceio"),
	@JsonProperty("America/Managua")
	America_Managua("America/Managua"),
	@JsonProperty("America/Manaus")
	America_Manaus("America/Manaus"),
	@JsonProperty("America/Marigot")
	America_Marigot("America/Marigot"),
	@JsonProperty("America/Martinique")
	America_Martinique("America/Martinique"),
	@JsonProperty("America/Matamoros")
	America_Matamoros("America/Matamoros"),
	@JsonProperty("America/Mazatlan")
	America_Mazatlan("America/Mazatlan"),
	@JsonProperty("America/Menominee")
	America_Menominee("America/Menominee"),
	@JsonProperty("America/Merida")
	America_Merida("America/Merida"),
	@JsonProperty("America/Metlakatla")
	America_Metlakatla("America/Metlakatla"),
	@JsonProperty("America/Mexico_City")
	America_Mexico_City("America/Mexico_City"),
	@JsonProperty("America/Miquelon")
	America_Miquelon("America/Miquelon"),
	@JsonProperty("America/Moncton")
	America_Moncton("America/Moncton"),
	@JsonProperty("America/Monterrey")
	America_Monterrey("America/Monterrey"),
	@JsonProperty("America/Montevideo")
	America_Montevideo("America/Montevideo"),
	@JsonProperty("America/Montserrat")
	America_Montserrat("America/Montserrat"),
	@JsonProperty("America/Nassau")
	America_Nassau("America/Nassau"),
	@JsonProperty("America/New_York")
	America_New_York("America/New_York"),
	@JsonProperty("America/Nipigon")
	America_Nipigon("America/Nipigon"),
	@JsonProperty("America/Nome")
	America_Nome("America/Nome"),
	@JsonProperty("America/Noronha")
	America_Noronha("America/Noronha"),
	@JsonProperty("America/North_Dakota/Beulah")
	America_North_Dakota_Beulah("America/North_Dakota/Beulah"),
	@JsonProperty("America/North_Dakota/Center")
	America_North_Dakota_Center("America/North_Dakota/Center"),
	@JsonProperty("America/North_Dakota/New_Salem")
	America_North_Dakota_New_Salem("America/North_Dakota/New_Salem"),
	@JsonProperty("America/Ojinaga")
	America_Ojinaga("America/Ojinaga"),
	@JsonProperty("America/Panama")
	America_Panama("America/Panama"),
	@JsonProperty("America/Pangnirtung")
	America_Pangnirtung("America/Pangnirtung"),
	@JsonProperty("America/Paramaribo")
	America_Paramaribo("America/Paramaribo"),
	@JsonProperty("America/Phoenix")
	America_Phoenix("America/Phoenix"),
	@JsonProperty("America/Port-au-Prince")
	America_Port_au_Prince("America/Port-au-Prince"),
	@JsonProperty("America/Port_of_Spain")
	America_Port_of_Spain("America/Port_of_Spain"),
	@JsonProperty("America/Porto_Velho")
	America_Porto_Velho("America/Porto_Velho"),
	@JsonProperty("America/Puerto_Rico")
	America_Puerto_Rico("America/Puerto_Rico"),
	@JsonProperty("America/Rainy_River")
	America_Rainy_River("America/Rainy_River"),
	@JsonProperty("America/Rankin_Inlet")
	America_Rankin_Inlet("America/Rankin_Inlet"),
	@JsonProperty("America/Recife")
	America_Recife("America/Recife"),
	@JsonProperty("America/Regina")
	America_Regina("America/Regina"),
	@JsonProperty("America/Resolute")
	America_Resolute("America/Resolute"),
	@JsonProperty("America/Rio_Branco")
	America_Rio_Branco("America/Rio_Branco"),
	@JsonProperty("America/Santa_Isabel")
	America_Santa_Isabel("America/Santa_Isabel"),
	@JsonProperty("America/Santarem")
	America_Santarem("America/Santarem"),
	@JsonProperty("America/Santiago")
	America_Santiago("America/Santiago"),
	@JsonProperty("America/Santo_Domingo")
	America_Santo_Domingo("America/Santo_Domingo"),
	@JsonProperty("America/Sao_Paulo")
	America_Sao_Paulo("America/Sao_Paulo"),
	@JsonProperty("America/Scoresbysund")
	America_Scoresbysund("America/Scoresbysund"),
	@JsonProperty("America/Sitka")
	America_Sitka("America/Sitka"),
	@JsonProperty("America/St_Barthelemy")
	America_St_Barthelemy("America/St_Barthelemy"),
	@JsonProperty("America/St_Johns")
	America_St_Johns("America/St_Johns"),
	@JsonProperty("America/St_Kitts")
	America_St_Kitts("America/St_Kitts"),
	@JsonProperty("America/St_Lucia")
	America_St_Lucia("America/St_Lucia"),
	@JsonProperty("America/St_Thomas")
	America_St_Thomas("America/St_Thomas"),
	@JsonProperty("America/St_Vincent")
	America_St_Vincent("America/St_Vincent"),
	@JsonProperty("America/Swift_Current")
	America_Swift_Current("America/Swift_Current"),
	@JsonProperty("America/Tegucigalpa")
	America_Tegucigalpa("America/Tegucigalpa"),
	@JsonProperty("America/Thule")
	America_Thule("America/Thule"),
	@JsonProperty("America/Thunder_Bay")
	America_Thunder_Bay("America/Thunder_Bay"),
	@JsonProperty("America/Tijuana")
	America_Tijuana("America/Tijuana"),
	@JsonProperty("America/Toronto")
	America_Toronto("America/Toronto"),
	@JsonProperty("America/Tortola")
	America_Tortola("America/Tortola"),
	@JsonProperty("America/Vancouver")
	America_Vancouver("America/Vancouver"),
	@JsonProperty("America/Whitehorse")
	America_Whitehorse("America/Whitehorse"),
	@JsonProperty("America/Winnipeg")
	America_Winnipeg("America/Winnipeg"),
	@JsonProperty("America/Yakutat")
	America_Yakutat("America/Yakutat"),
	@JsonProperty("America/Yellowknife")
	America_Yellowknife("America/Yellowknife"),
	@JsonProperty("Antarctica/Casey")
	Antarctica_Casey("Antarctica/Casey"),
	@JsonProperty("Antarctica/Davis")
	Antarctica_Davis("Antarctica/Davis"),
	@JsonProperty("Antarctica/DumontDUrville")
	Antarctica_DumontDUrville("Antarctica/DumontDUrville"),
	@JsonProperty("Antarctica/Macquarie")
	Antarctica_Macquarie("Antarctica/Macquarie"),
	@JsonProperty("Antarctica/Mawson")
	Antarctica_Mawson("Antarctica/Mawson"),
	@JsonProperty("Antarctica/McMurdo")
	Antarctica_McMurdo("Antarctica/McMurdo"),
	@JsonProperty("Antarctica/Palmer")
	Antarctica_Palmer("Antarctica/Palmer"),
	@JsonProperty("Antarctica/Rothera")
	Antarctica_Rothera("Antarctica/Rothera"),
	@JsonProperty("Antarctica/Syowa")
	Antarctica_Syowa("Antarctica/Syowa"),
	@JsonProperty("Antarctica/Troll")
	Antarctica_Troll("Antarctica/Troll"),
	@JsonProperty("Antarctica/Vostok")
	Antarctica_Vostok("Antarctica/Vostok"),
	@JsonProperty("Arctic/Longyearbyen")
	Arctic_Longyearbyen("Arctic/Longyearbyen"),
	@JsonProperty("Asia/Aden")
	Asia_Aden("Asia/Aden"),
	@JsonProperty("Asia/Almaty")
	Asia_Almaty("Asia/Almaty"),
	@JsonProperty("Asia/Amman")
	Asia_Amman("Asia/Amman"),
	@JsonProperty("Asia/Anadyr")
	Asia_Anadyr("Asia/Anadyr"),
	@JsonProperty("Asia/Aqtau")
	Asia_Aqtau("Asia/Aqtau"),
	@JsonProperty("Asia/Aqtobe")
	Asia_Aqtobe("Asia/Aqtobe"),
	@JsonProperty("Asia/Ashgabat")
	Asia_Ashgabat("Asia/Ashgabat"),
	@JsonProperty("Asia/Baghdad")
	Asia_Baghdad("Asia/Baghdad"),
	@JsonProperty("Asia/Bahrain")
	Asia_Bahrain("Asia/Bahrain"),
	@JsonProperty("Asia/Baku")
	Asia_Baku("Asia/Baku"),
	@JsonProperty("Asia/Bangkok")
	Asia_Bangkok("Asia/Bangkok"),
	@JsonProperty("Asia/Beirut")
	Asia_Beirut("Asia/Beirut"),
	@JsonProperty("Asia/Bishkek")
	Asia_Bishkek("Asia/Bishkek"),
	@JsonProperty("Asia/Brunei")
	Asia_Brunei("Asia/Brunei"),
	@JsonProperty("Asia/Chita")
	Asia_Chita("Asia/Chita"),
	@JsonProperty("Asia/Choibalsan")
	Asia_Choibalsan("Asia/Choibalsan"),
	@JsonProperty("Asia/Colombo")
	Asia_Colombo("Asia/Colombo"),
	@JsonProperty("Asia/Damascus")
	Asia_Damascus("Asia/Damascus"),
	@JsonProperty("Asia/Dhaka")
	Asia_Dhaka("Asia/Dhaka"),
	@JsonProperty("Asia/Dili")
	Asia_Dili("Asia/Dili"),
	@JsonProperty("Asia/Dubai")
	Asia_Dubai("Asia/Dubai"),
	@JsonProperty("Asia/Dushanbe")
	Asia_Dushanbe("Asia/Dushanbe"),
	@JsonProperty("Asia/Gaza")
	Asia_Gaza("Asia/Gaza"),
	@JsonProperty("Asia/Hebron")
	Asia_Hebron("Asia/Hebron"),
	@JsonProperty("Asia/Ho_Chi_Minh")
	Asia_Ho_Chi_Minh("Asia/Ho_Chi_Minh"),
	@JsonProperty("Asia/Hong_Kong")
	Asia_Hong_Kong("Asia/Hong_Kong"),
	@JsonProperty("Asia/Hovd")
	Asia_Hovd("Asia/Hovd"),
	@JsonProperty("Asia/Irkutsk")
	Asia_Irkutsk("Asia/Irkutsk"),
	@JsonProperty("Asia/Jakarta")
	Asia_Jakarta("Asia/Jakarta"),
	@JsonProperty("Asia/Jayapura")
	Asia_Jayapura("Asia/Jayapura"),
	@JsonProperty("Asia/Jerusalem")
	Asia_Jerusalem("Asia/Jerusalem"),
	@JsonProperty("Asia/Kabul")
	Asia_Kabul("Asia/Kabul"),
	@JsonProperty("Asia/Kamchatka")
	Asia_Kamchatka("Asia/Kamchatka"),
	@JsonProperty("Asia/Karachi")
	Asia_Karachi("Asia/Karachi"),
	@JsonProperty("Asia/Kathmandu")
	Asia_Kathmandu("Asia/Kathmandu"),
	@JsonProperty("Asia/Khandyga")
	Asia_Khandyga("Asia/Khandyga"),
	@JsonProperty("Asia/Kolkata")
	Asia_Kolkata("Asia/Kolkata"),
	@JsonProperty("Asia/Krasnoyarsk")
	Asia_Krasnoyarsk("Asia/Krasnoyarsk"),
	@JsonProperty("Asia/Kuala_Lumpur")
	Asia_Kuala_Lumpur("Asia/Kuala_Lumpur"),
	@JsonProperty("Asia/Kuching")
	Asia_Kuching("Asia/Kuching"),
	@JsonProperty("Asia/Kuwait")
	Asia_Kuwait("Asia/Kuwait"),
	@JsonProperty("Asia/Macau")
	Asia_Macau("Asia/Macau"),
	@JsonProperty("Asia/Magadan")
	Asia_Magadan("Asia/Magadan"),
	@JsonProperty("Asia/Makassar")
	Asia_Makassar("Asia/Makassar"),
	@JsonProperty("Asia/Manila")
	Asia_Manila("Asia/Manila"),
	@JsonProperty("Asia/Muscat")
	Asia_Muscat("Asia/Muscat"),
	@JsonProperty("Asia/Nicosia")
	Asia_Nicosia("Asia/Nicosia"),
	@JsonProperty("Asia/Novokuznetsk")
	Asia_Novokuznetsk("Asia/Novokuznetsk"),
	@JsonProperty("Asia/Novosibirsk")
	Asia_Novosibirsk("Asia/Novosibirsk"),
	@JsonProperty("Asia/Omsk")
	Asia_Omsk("Asia/Omsk"),
	@JsonProperty("Asia/Oral")
	Asia_Oral("Asia/Oral"),
	@JsonProperty("Asia/Phnom_Penh")
	Asia_Phnom_Penh("Asia/Phnom_Penh"),
	@JsonProperty("Asia/Pontianak")
	Asia_Pontianak("Asia/Pontianak"),
	@JsonProperty("Asia/Pyongyang")
	Asia_Pyongyang("Asia/Pyongyang"),
	@JsonProperty("Asia/Qatar")
	Asia_Qatar("Asia/Qatar"),
	@JsonProperty("Asia/Qyzylorda")
	Asia_Qyzylorda("Asia/Qyzylorda"),
	@JsonProperty("Asia/Rangoon")
	Asia_Rangoon("Asia/Rangoon"),
	@JsonProperty("Asia/Riyadh")
	Asia_Riyadh("Asia/Riyadh"),
	@JsonProperty("Asia/Sakhalin")
	Asia_Sakhalin("Asia/Sakhalin"),
	@JsonProperty("Asia/Samarkand")
	Asia_Samarkand("Asia/Samarkand"),
	@JsonProperty("Asia/Seoul")
	Asia_Seoul("Asia/Seoul"),
	@JsonProperty("Asia/Shanghai")
	Asia_Shanghai("Asia/Shanghai"),
	@JsonProperty("Asia/Singapore")
	Asia_Singapore("Asia/Singapore"),
	@JsonProperty("Asia/Srednekolymsk")
	Asia_Srednekolymsk("Asia/Srednekolymsk"),
	@JsonProperty("Asia/Taipei")
	Asia_Taipei("Asia/Taipei"),
	@JsonProperty("Asia/Tashkent")
	Asia_Tashkent("Asia/Tashkent"),
	@JsonProperty("Asia/Tbilisi")
	Asia_Tbilisi("Asia/Tbilisi"),
	@JsonProperty("Asia/Tehran")
	Asia_Tehran("Asia/Tehran"),
	@JsonProperty("Asia/Thimphu")
	Asia_Thimphu("Asia/Thimphu"),
	@JsonProperty("Asia/Tokyo")
	Asia_Tokyo("Asia/Tokyo"),
	@JsonProperty("Asia/Ulaanbaatar")
	Asia_Ulaanbaatar("Asia/Ulaanbaatar"),
	@JsonProperty("Asia/Urumqi")
	Asia_Urumqi("Asia/Urumqi"),
	@JsonProperty("Asia/Ust-Nera")
	Asia_Ust_Nera("Asia/Ust-Nera"),
	@JsonProperty("Asia/Vientiane")
	Asia_Vientiane("Asia/Vientiane"),
	@JsonProperty("Asia/Vladivostok")
	Asia_Vladivostok("Asia/Vladivostok"),
	@JsonProperty("Asia/Yakutsk")
	Asia_Yakutsk("Asia/Yakutsk"),
	@JsonProperty("Asia/Yekaterinburg")
	Asia_Yekaterinburg("Asia/Yekaterinburg"),
	@JsonProperty("Asia/Yerevan")
	Asia_Yerevan("Asia/Yerevan"),
	@JsonProperty("Atlantic/Azores")
	Atlantic_Azores("Atlantic/Azores"),
	@JsonProperty("Atlantic/Bermuda")
	Atlantic_Bermuda("Atlantic/Bermuda"),
	@JsonProperty("Atlantic/Canary")
	Atlantic_Canary("Atlantic/Canary"),
	@JsonProperty("Atlantic/Cape_Verde")
	Atlantic_Cape_Verde("Atlantic/Cape_Verde"),
	@JsonProperty("Atlantic/Faroe")
	Atlantic_Faroe("Atlantic/Faroe"),
	@JsonProperty("Atlantic/Madeira")
	Atlantic_Madeira("Atlantic/Madeira"),
	@JsonProperty("Atlantic/Reykjavik")
	Atlantic_Reykjavik("Atlantic/Reykjavik"),
	@JsonProperty("Atlantic/South_Georgia")
	Atlantic_South_Georgia("Atlantic/South_Georgia"),
	@JsonProperty("Atlantic/St_Helena")
	Atlantic_St_Helena("Atlantic/St_Helena"),
	@JsonProperty("Atlantic/Stanley")
	Atlantic_Stanley("Atlantic/Stanley"),
	@JsonProperty("Australia/Adelaide")
	Australia_Adelaide("Australia/Adelaide"),
	@JsonProperty("Australia/Brisbane")
	Australia_Brisbane("Australia/Brisbane"),
	@JsonProperty("Australia/Broken_Hill")
	Australia_Broken_Hill("Australia/Broken_Hill"),
	@JsonProperty("Australia/Currie")
	Australia_Currie("Australia/Currie"),
	@JsonProperty("Australia/Darwin")
	Australia_Darwin("Australia/Darwin"),
	@JsonProperty("Australia/Eucla")
	Australia_Eucla("Australia/Eucla"),
	@JsonProperty("Australia/Hobart")
	Australia_Hobart("Australia/Hobart"),
	@JsonProperty("Australia/Lindeman")
	Australia_Lindeman("Australia/Lindeman"),
	@JsonProperty("Australia/Lord_Howe")
	Australia_Lord_Howe("Australia/Lord_Howe"),
	@JsonProperty("Australia/Melbourne")
	Australia_Melbourne("Australia/Melbourne"),
	@JsonProperty("Australia/Perth")
	Australia_Perth("Australia/Perth"),
	@JsonProperty("Australia/Sydney")
	Australia_Sydney("Australia/Sydney"),
	@JsonProperty("Europe/Amsterdam")
	Europe_Amsterdam("Europe/Amsterdam"),
	@JsonProperty("Europe/Andorra")
	Europe_Andorra("Europe/Andorra"),
	@JsonProperty("Europe/Athens")
	Europe_Athens("Europe/Athens"),
	@JsonProperty("Europe/Belgrade")
	Europe_Belgrade("Europe/Belgrade"),
	@JsonProperty("Europe/Berlin")
	Europe_Berlin("Europe/Berlin"),
	@JsonProperty("Europe/Bratislava")
	Europe_Bratislava("Europe/Bratislava"),
	@JsonProperty("Europe/Brussels")
	Europe_Brussels("Europe/Brussels"),
	@JsonProperty("Europe/Bucharest")
	Europe_Bucharest("Europe/Bucharest"),
	@JsonProperty("Europe/Budapest")
	Europe_Budapest("Europe/Budapest"),
	@JsonProperty("Europe/Busingen")
	Europe_Busingen("Europe/Busingen"),
	@JsonProperty("Europe/Chisinau")
	Europe_Chisinau("Europe/Chisinau"),
	@JsonProperty("Europe/Copenhagen")
	Europe_Copenhagen("Europe/Copenhagen"),
	@JsonProperty("Europe/Dublin")
	Europe_Dublin("Europe/Dublin"),
	@JsonProperty("Europe/Gibraltar")
	Europe_Gibraltar("Europe/Gibraltar"),
	@JsonProperty("Europe/Guernsey")
	Europe_Guernsey("Europe/Guernsey"),
	@JsonProperty("Europe/Helsinki")
	Europe_Helsinki("Europe/Helsinki"),
	@JsonProperty("Europe/Isle_of_Man")
	Europe_Isle_of_Man("Europe/Isle_of_Man"),
	@JsonProperty("Europe/Istanbul")
	Europe_Istanbul("Europe/Istanbul"),
	@JsonProperty("Europe/Jersey")
	Europe_Jersey("Europe/Jersey"),
	@JsonProperty("Europe/Kaliningrad")
	Europe_Kaliningrad("Europe/Kaliningrad"),
	@JsonProperty("Europe/Kiev")
	Europe_Kiev("Europe/Kiev"),
	@JsonProperty("Europe/Lisbon")
	Europe_Lisbon("Europe/Lisbon"),
	@JsonProperty("Europe/Ljubljana")
	Europe_Ljubljana("Europe/Ljubljana"),
	@JsonProperty("Europe/London")
	Europe_London("Europe/London"),
	@JsonProperty("Europe/Luxembourg")
	Europe_Luxembourg("Europe/Luxembourg"),
	@JsonProperty("Europe/Madrid")
	Europe_Madrid("Europe/Madrid"),
	@JsonProperty("Europe/Malta")
	Europe_Malta("Europe/Malta"),
	@JsonProperty("Europe/Mariehamn")
	Europe_Mariehamn("Europe/Mariehamn"),
	@JsonProperty("Europe/Minsk")
	Europe_Minsk("Europe/Minsk"),
	@JsonProperty("Europe/Monaco")
	Europe_Monaco("Europe/Monaco"),
	@JsonProperty("Europe/Moscow")
	Europe_Moscow("Europe/Moscow"),
	@JsonProperty("Europe/Oslo")
	Europe_Oslo("Europe/Oslo"),
	@JsonProperty("Europe/Paris")
	Europe_Paris("Europe/Paris"),
	@JsonProperty("Europe/Podgorica")
	Europe_Podgorica("Europe/Podgorica"),
	@JsonProperty("Europe/Prague")
	Europe_Prague("Europe/Prague"),
	@JsonProperty("Europe/Riga")
	Europe_Riga("Europe/Riga"),
	@JsonProperty("Europe/Rome")
	Europe_Rome("Europe/Rome"),
	@JsonProperty("Europe/Samara")
	Europe_Samara("Europe/Samara"),
	@JsonProperty("Europe/San_Marino")
	Europe_San_Marino("Europe/San_Marino"),
	@JsonProperty("Europe/Sarajevo")
	Europe_Sarajevo("Europe/Sarajevo"),
	@JsonProperty("Europe/Simferopol")
	Europe_Simferopol("Europe/Simferopol"),
	@JsonProperty("Europe/Skopje")
	Europe_Skopje("Europe/Skopje"),
	@JsonProperty("Europe/Sofia")
	Europe_Sofia("Europe/Sofia"),
	@JsonProperty("Europe/Stockholm")
	Europe_Stockholm("Europe/Stockholm"),
	@JsonProperty("Europe/Tallinn")
	Europe_Tallinn("Europe/Tallinn"),
	@JsonProperty("Europe/Tirane")
	Europe_Tirane("Europe/Tirane"),
	@JsonProperty("Europe/Uzhgorod")
	Europe_Uzhgorod("Europe/Uzhgorod"),
	@JsonProperty("Europe/Vaduz")
	Europe_Vaduz("Europe/Vaduz"),
	@JsonProperty("Europe/Vatican")
	Europe_Vatican("Europe/Vatican"),
	@JsonProperty("Europe/Vienna")
	Europe_Vienna("Europe/Vienna"),
	@JsonProperty("Europe/Vilnius")
	Europe_Vilnius("Europe/Vilnius"),
	@JsonProperty("Europe/Volgograd")
	Europe_Volgograd("Europe/Volgograd"),
	@JsonProperty("Europe/Warsaw")
	Europe_Warsaw("Europe/Warsaw"),
	@JsonProperty("Europe/Zagreb")
	Europe_Zagreb("Europe/Zagreb"),
	@JsonProperty("Europe/Zaporozhye")
	Europe_Zaporozhye("Europe/Zaporozhye"),
	@JsonProperty("Europe/Zurich")
	Europe_Zurich("Europe/Zurich"),
	@JsonProperty("Indian/Antananarivo")
	Indian_Antananarivo("Indian/Antananarivo"),
	@JsonProperty("Indian/Chagos")
	Indian_Chagos("Indian/Chagos"),
	@JsonProperty("Indian/Christmas")
	Indian_Christmas("Indian/Christmas"),
	@JsonProperty("Indian/Cocos")
	Indian_Cocos("Indian/Cocos"),
	@JsonProperty("Indian/Comoro")
	Indian_Comoro("Indian/Comoro"),
	@JsonProperty("Indian/Kerguelen")
	Indian_Kerguelen("Indian/Kerguelen"),
	@JsonProperty("Indian/Mahe")
	Indian_Mahe("Indian/Mahe"),
	@JsonProperty("Indian/Maldives")
	Indian_Maldives("Indian/Maldives"),
	@JsonProperty("Indian/Mauritius")
	Indian_Mauritius("Indian/Mauritius"),
	@JsonProperty("Indian/Mayotte")
	Indian_Mayotte("Indian/Mayotte"),
	@JsonProperty("Indian/Reunion")
	Indian_Reunion("Indian/Reunion"),
	@JsonProperty("Pacific/Apia")
	Pacific_Apia("Pacific/Apia"),
	@JsonProperty("Pacific/Auckland")
	Pacific_Auckland("Pacific/Auckland"),
	@JsonProperty("Pacific/Bougainville")
	Pacific_Bougainville("Pacific/Bougainville"),
	@JsonProperty("Pacific/Chatham")
	Pacific_Chatham("Pacific/Chatham"),
	@JsonProperty("Pacific/Chuuk")
	Pacific_Chuuk("Pacific/Chuuk"),
	@JsonProperty("Pacific/Easter")
	Pacific_Easter("Pacific/Easter"),
	@JsonProperty("Pacific/Efate")
	Pacific_Efate("Pacific/Efate"),
	@JsonProperty("Pacific/Enderbury")
	Pacific_Enderbury("Pacific/Enderbury"),
	@JsonProperty("Pacific/Fakaofo")
	Pacific_Fakaofo("Pacific/Fakaofo"),
	@JsonProperty("Pacific/Fiji")
	Pacific_Fiji("Pacific/Fiji"),
	@JsonProperty("Pacific/Funafuti")
	Pacific_Funafuti("Pacific/Funafuti"),
	@JsonProperty("Pacific/Galapagos")
	Pacific_Galapagos("Pacific/Galapagos"),
	@JsonProperty("Pacific/Gambier")
	Pacific_Gambier("Pacific/Gambier"),
	@JsonProperty("Pacific/Guadalcanal")
	Pacific_Guadalcanal("Pacific/Guadalcanal"),
	@JsonProperty("Pacific/Guam")
	Pacific_Guam("Pacific/Guam"),
	@JsonProperty("Pacific/Honolulu")
	Pacific_Honolulu("Pacific/Honolulu"),
	@JsonProperty("Pacific/Johnston")
	Pacific_Johnston("Pacific/Johnston"),
	@JsonProperty("Pacific/Kiritimati")
	Pacific_Kiritimati("Pacific/Kiritimati"),
	@JsonProperty("Pacific/Kosrae")
	Pacific_Kosrae("Pacific/Kosrae"),
	@JsonProperty("Pacific/Kwajalein")
	Pacific_Kwajalein("Pacific/Kwajalein"),
	@JsonProperty("Pacific/Majuro")
	Pacific_Majuro("Pacific/Majuro"),
	@JsonProperty("Pacific/Marquesas")
	Pacific_Marquesas("Pacific/Marquesas"),
	@JsonProperty("Pacific/Midway")
	Pacific_Midway("Pacific/Midway"),
	@JsonProperty("Pacific/Nauru")
	Pacific_Nauru("Pacific/Nauru"),
	@JsonProperty("Pacific/Niue")
	Pacific_Niue("Pacific/Niue"),
	@JsonProperty("Pacific/Norfolk")
	Pacific_Norfolk("Pacific/Norfolk"),
	@JsonProperty("Pacific/Noumea")
	Pacific_Noumea("Pacific/Noumea"),
	@JsonProperty("Pacific/Pago_Pago")
	Pacific_Pago_Pago("Pacific/Pago_Pago"),
	@JsonProperty("Pacific/Palau")
	Pacific_Palau("Pacific/Palau"),
	@JsonProperty("Pacific/Pitcairn")
	Pacific_Pitcairn("Pacific/Pitcairn"),
	@JsonProperty("Pacific/Pohnpei")
	Pacific_Pohnpei("Pacific/Pohnpei"),
	@JsonProperty("Pacific/Port_Moresby")
	Pacific_Port_Moresby("Pacific/Port_Moresby"),
	@JsonProperty("Pacific/Rarotonga")
	Pacific_Rarotonga("Pacific/Rarotonga"),
	@JsonProperty("Pacific/Saipan")
	Pacific_Saipan("Pacific/Saipan"),
	@JsonProperty("Pacific/Tahiti")
	Pacific_Tahiti("Pacific/Tahiti"),
	@JsonProperty("Pacific/Tarawa")
	Pacific_Tarawa("Pacific/Tarawa"),
	@JsonProperty("Pacific/Tongatapu")
	Pacific_Tongatapu("Pacific/Tongatapu"),
	@JsonProperty("Pacific/Wake")
	Pacific_Wake("Pacific/Wake"),
	@JsonProperty("Pacific/Wallis")
	Pacific_Wallis("Pacific/Wallis");

	final String value;

	OvhTimeZoneEnum(String s) {
		this.value = s;
	}

	public String toString() {
		return this.value;
	}
}
