package net.minidev.ovh.api.metrics.api;

/**
 * Access to the metrics of your service
 */
public class OvhMetricsAccess {
	/**
	 * The endpoint address to get metrics from
	 *
	 * canBeNull && readOnly
	 */
	public String endpoint;

	/**
	 * Token to used to access your metrics generated by your service
	 *
	 * canBeNull && readOnly
	 */
	public String accessToken;
}
